name: day_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-296.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  supabase_flutter: ^2.12.0
  supabase_auth_ui: ^0.5.5
  hive_flutter: ^1.1.0
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  intl: ^0.20.2
  get_storage: ^2.1.1
  google_fonts: ^8.0.1
  flutter_svg: ^2.2.3
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_ill.svg
    - assets/images/logo.svg
